version: "3"
services:
  app:
    build:
      context: .
    container_name: nginx-dns-map
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/www/:/var/www/

networks:
  default:
    external:
      name: onsite-net
